// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAk-Hllv-RuoVdHVF-JQjHIj--FstcrOmE',
    appId: '1:12158695753:android:8832ff4b6a6d6e934a4298',
    messagingSenderId: '12158695753',
    projectId: 'vinopener-dd490',
    storageBucket: 'vinopener-dd490.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfma6z7m7IFEzjUQwy9CTcTMdnZhRu2jU',
    appId: '1:12158695753:ios:af46dbcd7b8133e04a4298',
    messagingSenderId: '12158695753',
    projectId: 'vinopener-dd490',
    storageBucket: 'vinopener-dd490.appspot.com',
    androidClientId: '12158695753-rg0g5lr1iuola4b0gu3kep9ri9dqv1e6.apps.googleusercontent.com',
    iosClientId: '12158695753-949m1boqr16g842clibr58mqgembi5sp.apps.googleusercontent.com',
    iosBundleId: 'com.vinopener.frontend',
  );

}